version: '3.8'

services:
  web:
    build: .
    container_name: zrozumto-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./temp_ingest:/app/temp_ingest # Persist temp folder if needed, or mapping for debug
    environment:
      - WATCHFILES_FORCE_POLLING=true

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
  environment:
   - N8N_HOST=n8n.zrozum-to.pl
   - N8N_PORT=5678
    - N8N_PROTOCOL=https
    - WEBHOOK_URL=https://n8n.zrozum-to.pl/
    - GENERIC_TIMEZONE=Europe/Warsaw
    - NODE_OPTIONS=--max-old-space-size=1024
    - EXECUTIONS_PROCESS=main
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:


